import React, { useState } from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useCandidateAuth } from '../context/CandidateAuthContext.jsx';

const links=[['/candidate/dashboard','Dashboard','⌂'],['/candidate/interviews','My interviews','▣'],['/candidate/profile','Profile','◎']];
export default function CandidateLayout(){const{account,logout}=useCandidateAuth();const navigate=useNavigate();const[open,setOpen]=useState(false);function signOut(){logout();navigate('/candidate/login',{replace:true});}const nav=<nav className="space-y-1">{links.map(([to,label,icon])=><NavLink key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold transition ${isActive?'bg-brand-500 text-white shadow-lg shadow-indigo-950/20':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><span className="grid h-7 w-7 place-items-center rounded-lg bg-white/5">{icon}</span>{label}</NavLink>)}</nav>;
return <div className="min-h-screen bg-[#070b14] text-slate-100"><header className="sticky top-0 z-40 border-b border-slate-800 bg-[#09101d]/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><button className="grid h-10 w-10 place-items-center rounded-xl border border-slate-700 lg:hidden" onClick={()=>setOpen(true)} aria-label="Open menu">☰</button><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand-500 font-black text-white">T</span><div><strong className="block">TalentLens Candidate</strong><span className="text-xs text-slate-500">Automated interview portal</span></div></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><strong className="block text-sm">{account?.profile?.fullName||account?.email}</strong><span className="text-xs text-slate-500">Candidate account</span></div><button onClick={signOut} className="rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold text-slate-300 hover:border-slate-500 hover:text-white">Logout</button></div></div></header>
<div className="mx-auto grid max-w-[1500px] gap-8 px-5 py-8 lg:grid-cols-[240px_minmax(0,1fr)] lg:px-8"><aside className="hidden lg:block"><div className="sticky top-28 rounded-2xl border border-slate-800 bg-[#0b1220] p-2">{nav}<div className="mt-3 border-t border-slate-800 p-3 text-xs leading-5 text-slate-600">Your interview data is private and visible only to authorized hiring staff.</div></div></aside><main className="min-w-0"><Outlet/></main></div>
{open&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/70" onClick={()=>setOpen(false)} aria-label="Close menu"/><aside className="relative h-full w-[290px] border-r border-slate-800 bg-[#0b1220] p-4"><div className="mb-6 flex items-center justify-between"><strong>Candidate menu</strong><button onClick={()=>setOpen(false)}>✕</button></div>{nav}</aside></div>}</div>;
}
