import React, { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext.jsx';
import { getOrganization, updateOrganization } from '../services/organizationService.js';

const inputClass = 'w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5 text-sm text-white outline-none focus:border-brand-400 focus:ring-4 focus:ring-brand-500/10';
const emptyAddress = { line1: '', line2: '', city: '', state: '', country: '', postalCode: '' };
const defaults = { name: '', legalName: '', industry: '', companySize: '', foundedYear: '', website: '', email: '', phone: '', taxId: '', registrationNumber: '', description: '', logoUrl: '', brandColor: '#6366F1', linkedinUrl: '', twitterUrl: '', address: emptyAddress, timezone: 'Asia/Kolkata', dateFormat: 'DD/MM/YYYY', currency: 'INR', defaultHiringEmail: '', defaultInterviewDuration: 45, workingDays: ['Monday','Tuesday','Wednesday','Thursday','Friday'] };
const days = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];

function Field({ label, children }) { return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">{label}</span>{children}</label>; }
function Section({ title, description, children }) { return <section className="rounded-2xl border border-slate-800 bg-[#0b1220] p-5 md:p-6"><div className="mb-5"><h2 className="text-lg font-black">{title}</h2>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{children}</section>; }

export default function OrganizationSettingsPage() {
  const { user, updateCurrentUser } = useAuth();
  const [form, setForm] = useState(defaults); const [organization, setOrganization] = useState(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  useEffect(() => { getOrganization().then((data) => { setOrganization(data); setForm({ ...defaults, ...data, foundedYear: data.foundedYear || '', address: { ...emptyAddress, ...(data.address || {}) }, workingDays: data.workingDays || defaults.workingDays }); }).catch((err) => setError(err.response?.data?.message || 'Unable to load organization.')).finally(() => setLoading(false)); }, []);
  const set = (key, value) => setForm((v) => ({ ...v, [key]: value }));
  const setAddress = (key, value) => setForm((v) => ({ ...v, address: { ...v.address, [key]: value } }));
  function toggleDay(day) { setForm((v) => ({ ...v, workingDays: v.workingDays.includes(day) ? v.workingDays.filter((item) => item !== day) : [...v.workingDays, day] })); }
  async function submit(event) { event.preventDefault(); setSaving(true); setMessage(''); setError(''); try { const payload = { ...form, foundedYear: form.foundedYear ? Number(form.foundedYear) : null, defaultInterviewDuration: Number(form.defaultInterviewDuration) }; const updated = await updateOrganization(payload); setOrganization(updated); setForm((v) => ({ ...v, ...updated, foundedYear: updated.foundedYear || '' })); updateCurrentUser({ ...user, organization: { ...user.organization, name: updated.name } }); setMessage('Organization profile saved successfully.'); window.scrollTo({ top: 0, behavior: 'smooth' }); } catch (err) { setError(err.response?.data?.message || 'Unable to update organization.'); } finally { setSaving(false); } }
  if (loading) return <div className="p-8 text-sm text-slate-400">Loading organization…</div>;
  return <form onSubmit={submit} className="mx-auto max-w-6xl space-y-6"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><span className="text-xs font-black uppercase tracking-[.2em] text-brand-400">Administration</span><h1 className="mt-2 text-3xl font-black">Organization profile</h1><p className="mt-2 text-sm text-slate-400">Company identity, contact details, branding, and hiring preferences.</p></div><button disabled={saving} className="rounded-xl bg-brand-500 px-5 py-3 text-sm font-black text-white hover:bg-brand-600 disabled:opacity-60">{saving ? 'Saving…' : 'Save organization'}</button></header>
    {(message || error) && <div className={`rounded-xl border p-3 text-sm ${error ? 'border-rose-500/30 bg-rose-500/10 text-rose-300' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'}`}>{error || message}</div>}
    <Section title="Company information" description="Core organization and legal details."><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><Field label="Organization name *"><input className={inputClass} value={form.name} required minLength="2" onChange={(e) => set('name', e.target.value)} /></Field><Field label="Legal company name"><input className={inputClass} value={form.legalName} onChange={(e) => set('legalName', e.target.value)} /></Field><Field label="Industry"><input className={inputClass} value={form.industry} placeholder="Technology" onChange={(e) => set('industry', e.target.value)} /></Field><Field label="Company size"><select className={inputClass} value={form.companySize} onChange={(e) => set('companySize', e.target.value)}><option value="">Select size</option>{['1-10','11-50','51-200','201-500','501-1000','1000+'].map((x)=><option key={x}>{x}</option>)}</select></Field><Field label="Founded year"><input className={inputClass} type="number" min="1800" max="2200" value={form.foundedYear} onChange={(e) => set('foundedYear', e.target.value)} /></Field><Field label="Workspace slug"><input className={`${inputClass} opacity-60`} value={organization?.slug || ''} disabled /></Field><Field label="Website"><input className={inputClass} value={form.website} placeholder="https://company.com" onChange={(e) => set('website', e.target.value)} /></Field><Field label="Company email"><input className={inputClass} type="email" value={form.email} onChange={(e) => set('email', e.target.value)} /></Field><Field label="Phone"><input className={inputClass} value={form.phone} onChange={(e) => set('phone', e.target.value)} /></Field><Field label="GST / Tax ID"><input className={inputClass} value={form.taxId} onChange={(e) => set('taxId', e.target.value)} /></Field><Field label="Registration number"><input className={inputClass} value={form.registrationNumber} onChange={(e) => set('registrationNumber', e.target.value)} /></Field></div><Field label="Company description"><textarea className={`${inputClass} mt-5 min-h-32 resize-y`} value={form.description} onChange={(e) => set('description', e.target.value)} /></Field></Section>
    <Section title="Branding and social presence"><div className="grid gap-5 md:grid-cols-2"><Field label="Logo URL"><input className={inputClass} value={form.logoUrl} placeholder="https://.../logo.png" onChange={(e) => set('logoUrl', e.target.value)} /></Field><Field label="Brand color"><div className="flex gap-3"><input className="h-11 w-16 rounded-lg border border-slate-700 bg-slate-950 p-1" type="color" value={form.brandColor || '#6366F1'} onChange={(e) => set('brandColor', e.target.value)} /><input className={inputClass} value={form.brandColor} onChange={(e) => set('brandColor', e.target.value)} /></div></Field><Field label="LinkedIn"><input className={inputClass} value={form.linkedinUrl} onChange={(e) => set('linkedinUrl', e.target.value)} /></Field><Field label="Twitter / X"><input className={inputClass} value={form.twitterUrl} onChange={(e) => set('twitterUrl', e.target.value)} /></Field></div></Section>
    <Section title="Office address"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><Field label="Address line 1"><input className={inputClass} value={form.address.line1} onChange={(e) => setAddress('line1', e.target.value)} /></Field><Field label="Address line 2"><input className={inputClass} value={form.address.line2} onChange={(e) => setAddress('line2', e.target.value)} /></Field><Field label="City"><input className={inputClass} value={form.address.city} onChange={(e) => setAddress('city', e.target.value)} /></Field><Field label="State"><input className={inputClass} value={form.address.state} onChange={(e) => setAddress('state', e.target.value)} /></Field><Field label="Country"><input className={inputClass} value={form.address.country} onChange={(e) => setAddress('country', e.target.value)} /></Field><Field label="Postal code"><input className={inputClass} value={form.address.postalCode} onChange={(e) => setAddress('postalCode', e.target.value)} /></Field></div></Section>
    <Section title="Hiring preferences"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Timezone"><input className={inputClass} value={form.timezone} onChange={(e) => set('timezone', e.target.value)} /></Field><Field label="Date format"><select className={inputClass} value={form.dateFormat} onChange={(e) => set('dateFormat', e.target.value)}><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></Field><Field label="Currency"><input className={inputClass} value={form.currency} maxLength="10" onChange={(e) => set('currency', e.target.value.toUpperCase())} /></Field><Field label="Interview duration (minutes)"><input className={inputClass} type="number" min="10" max="480" value={form.defaultInterviewDuration} onChange={(e) => set('defaultInterviewDuration', e.target.value)} /></Field><Field label="Default hiring email"><input className={inputClass} type="email" value={form.defaultHiringEmail} onChange={(e) => set('defaultHiringEmail', e.target.value)} /></Field></div><div className="mt-5"><span className="mb-3 block text-sm font-bold text-slate-300">Working days</span><div className="flex flex-wrap gap-2">{days.map((day)=><button type="button" key={day} onClick={()=>toggleDay(day)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${form.workingDays.includes(day) ? 'border-brand-400 bg-brand-500/15 text-brand-300' : 'border-slate-700 text-slate-400 hover:bg-slate-800'}`}>{day}</button>)}</div></div></Section>
    <div className="flex justify-end"><button disabled={saving} className="rounded-xl bg-brand-500 px-6 py-3 text-sm font-black text-white hover:bg-brand-600 disabled:opacity-60">{saving ? 'Saving…' : 'Save organization'}</button></div>
  </form>;
}
