import React, { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.jsx';
import { changePassword, updateProfile } from '../services/profileService.js';
import { ROLE_LABELS } from '../constants/roles.js';

const inputClass = 'w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5 text-sm text-white outline-none focus:border-brand-400 focus:ring-4 focus:ring-brand-500/10';
const emptyAddress = { line1: '', line2: '', city: '', state: '', country: '', postalCode: '' };
function Field({ label, children }) { return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">{label}</span>{children}</label>; }
function EyeIcon({ visible }) { return <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">{visible ? <><path d="M3 3l18 18"/><path d="M10.7 10.7a2 2 0 0 0 2.6 2.6M9.8 4.2A10 10 0 0 1 12 4c5.5 0 9 5.1 9 8a8 8 0 0 1-2 3.7M6.6 6.6C4.2 8.2 3 10.5 3 12c0 2.9 3.5 8 9 8a10 10 0 0 0 3.3-.6"/></> : <><path d="M3 12c0-2.9 3.5-8 9-8s9 5.1 9 8-3.5 8-9 8-9-5.1-9-8Z"/><circle cx="12" cy="12" r="3"/></>}</svg>; }

export default function ProfilePage() {
  const { user, updateCurrentUser } = useAuth(); const [params, setParams] = useSearchParams();
  const activeTab = params.get('tab') === 'security' ? 'security' : 'profile';
  const initial = useMemo(() => ({ name: user?.name || '', avatarUrl: user?.avatarUrl || '', employeeId: user?.employeeId || '', department: user?.department || '', designation: user?.designation || '', phone: user?.phone || '', alternatePhone: user?.alternatePhone || '', dateOfBirth: user?.dateOfBirth ? String(user.dateOfBirth).slice(0,10) : '', gender: user?.gender || '', bio: user?.bio || '', skillsText: (user?.skills || []).join(', '), linkedinUrl: user?.linkedinUrl || '', githubUrl: user?.githubUrl || '', timezone: user?.timezone || 'Asia/Kolkata', language: user?.language || 'English', address: { ...emptyAddress, ...(user?.address || {}) }, emergencyContact: { name: '', relationship: '', phone: '', ...(user?.emergencyContact || {}) } }), [user]);
  const [form, setForm] = useState(initial); const [password, setPassword] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });
  const [showPassword, setShowPassword] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const set = (key, value) => setForm((v)=>({ ...v, [key]: value })); const setNested = (group,key,value)=>setForm((v)=>({ ...v, [group]: { ...v[group], [key]: value } }));
  async function saveProfile(e) { e.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const payload = { ...form, skills: form.skillsText.split(',').map((x)=>x.trim()).filter(Boolean), dateOfBirth: form.dateOfBirth || null }; delete payload.skillsText; const updated = await updateProfile(payload); updateCurrentUser(updated); setMessage('Profile saved successfully.'); } catch (err) { setError(err.response?.data?.message || 'Unable to update profile.'); } finally { setSaving(false); } }
  async function savePassword(e) { e.preventDefault(); setError(''); setMessage(''); if (password.newPassword !== password.confirmPassword) return setError('New passwords do not match.'); setSaving(true); try { const updated = await changePassword({ currentPassword: password.currentPassword, newPassword: password.newPassword }); updateCurrentUser(updated); setPassword({ currentPassword: '', newPassword: '', confirmPassword: '' }); setMessage('Password updated successfully.'); } catch (err) { setError(err.response?.data?.message || 'Unable to change password.'); } finally { setSaving(false); } }
  return <div className="mx-auto max-w-6xl space-y-6"><header><span className="text-xs font-black uppercase tracking-[.2em] text-brand-400">Account</span><h1 className="mt-2 text-3xl font-black">My profile</h1><p className="mt-2 text-sm text-slate-400">Manage personal, professional, and security information.</p></header>
    <div className="flex gap-2 rounded-xl border border-slate-800 bg-[#0b1220] p-1.5"><button onClick={()=>setParams({ tab:'profile' })} className={`rounded-lg px-4 py-2 text-sm font-bold ${activeTab==='profile'?'bg-brand-500 text-white':'text-slate-400 hover:text-white'}`}>Profile details</button><button onClick={()=>setParams({ tab:'security' })} className={`rounded-lg px-4 py-2 text-sm font-bold ${activeTab==='security'?'bg-brand-500 text-white':'text-slate-400 hover:text-white'}`}>Security & password</button></div>
    {(message || error) && <div className={`rounded-xl border p-3 text-sm ${error ? 'border-rose-500/30 bg-rose-500/10 text-rose-300' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'}`}>{error || message}</div>}
    {activeTab === 'profile' ? <form onSubmit={saveProfile} className="space-y-6"><section className="rounded-2xl border border-slate-800 bg-[#0b1220] p-5 md:p-6"><div className="mb-5 flex items-center gap-4"><span className="grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-brand-500 text-xl font-black">{form.avatarUrl ? <img src={form.avatarUrl} className="h-full w-full object-cover" alt="Profile"/> : (form.name || 'U').slice(0,1).toUpperCase()}</span><div><h2 className="text-lg font-black">Personal and work details</h2><p className="text-sm text-slate-500">Role: {ROLE_LABELS[user?.role] || user?.role}</p></div></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><Field label="Full name *"><input className={inputClass} required minLength="2" value={form.name} onChange={(e)=>set('name',e.target.value)}/></Field><Field label="Email"><input className={`${inputClass} opacity-60`} value={user?.email || ''} disabled/></Field><Field label="Profile picture URL"><input className={inputClass} value={form.avatarUrl} onChange={(e)=>set('avatarUrl',e.target.value)}/></Field><Field label="Employee ID"><input className={inputClass} value={form.employeeId} onChange={(e)=>set('employeeId',e.target.value)}/></Field><Field label="Department"><input className={inputClass} value={form.department} onChange={(e)=>set('department',e.target.value)}/></Field><Field label="Designation"><input className={inputClass} value={form.designation} onChange={(e)=>set('designation',e.target.value)}/></Field><Field label="Phone"><input className={inputClass} value={form.phone} onChange={(e)=>set('phone',e.target.value)}/></Field><Field label="Alternate phone"><input className={inputClass} value={form.alternatePhone} onChange={(e)=>set('alternatePhone',e.target.value)}/></Field><Field label="Date of birth"><input className={inputClass} type="date" value={form.dateOfBirth} onChange={(e)=>set('dateOfBirth',e.target.value)}/></Field><Field label="Gender"><input className={inputClass} value={form.gender} onChange={(e)=>set('gender',e.target.value)}/></Field><Field label="Timezone"><input className={inputClass} value={form.timezone} onChange={(e)=>set('timezone',e.target.value)}/></Field><Field label="Language"><input className={inputClass} value={form.language} onChange={(e)=>set('language',e.target.value)}/></Field><Field label="LinkedIn"><input className={inputClass} value={form.linkedinUrl} onChange={(e)=>set('linkedinUrl',e.target.value)}/></Field><Field label="GitHub"><input className={inputClass} value={form.githubUrl} onChange={(e)=>set('githubUrl',e.target.value)}/></Field></div><Field label="Skills (comma separated)"><input className={`${inputClass} mt-5`} value={form.skillsText} onChange={(e)=>set('skillsText',e.target.value)}/></Field><Field label="Professional bio"><textarea className={`${inputClass} mt-5 min-h-28 resize-y`} value={form.bio} onChange={(e)=>set('bio',e.target.value)}/></Field></section>
      <section className="rounded-2xl border border-slate-800 bg-[#0b1220] p-5 md:p-6"><h2 className="mb-5 text-lg font-black">Address and emergency contact</h2><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{Object.entries({line1:'Address line 1',line2:'Address line 2',city:'City',state:'State',country:'Country',postalCode:'Postal code'}).map(([k,l])=><Field key={k} label={l}><input className={inputClass} value={form.address[k]} onChange={(e)=>setNested('address',k,e.target.value)}/></Field>)}</div><div className="mt-6 grid gap-5 md:grid-cols-3"><Field label="Emergency contact name"><input className={inputClass} value={form.emergencyContact.name} onChange={(e)=>setNested('emergencyContact','name',e.target.value)}/></Field><Field label="Relationship"><input className={inputClass} value={form.emergencyContact.relationship} onChange={(e)=>setNested('emergencyContact','relationship',e.target.value)}/></Field><Field label="Emergency phone"><input className={inputClass} value={form.emergencyContact.phone} onChange={(e)=>setNested('emergencyContact','phone',e.target.value)}/></Field></div></section><div className="flex justify-end"><button disabled={saving} className="rounded-xl bg-brand-500 px-6 py-3 text-sm font-black text-white hover:bg-brand-600 disabled:opacity-60">{saving?'Saving…':'Save profile'}</button></div></form>
    : <form onSubmit={savePassword} className="mx-auto max-w-2xl rounded-2xl border border-slate-800 bg-[#0b1220] p-6"><h2 className="text-xl font-black">Change password</h2><p className="mt-1 text-sm text-slate-500">Use at least 8 characters and avoid reusing passwords.</p><div className="mt-6 space-y-4">{[['currentPassword','Current password'],['newPassword','New password'],['confirmPassword','Confirm new password']].map(([key,label])=><Field key={key} label={label}><div className="relative"><input className={`${inputClass} pr-12`} type={showPassword?'text':'password'} required minLength={key==='currentPassword'?1:8} value={password[key]} onChange={(e)=>setPassword((v)=>({...v,[key]:e.target.value}))}/><button type="button" onClick={()=>setShowPassword((v)=>!v)} className="absolute inset-y-0 right-2 grid w-9 place-items-center text-slate-400 hover:text-white" aria-label={showPassword?'Hide passwords':'Show passwords'}><EyeIcon visible={showPassword}/></button></div></Field>)}<button disabled={saving} className="w-full rounded-xl bg-brand-500 px-5 py-3 text-sm font-black text-white hover:bg-brand-600 disabled:opacity-60">{saving?'Updating…':'Update password'}</button></div></form>}
  </div>;
}
