import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import StatusBadge from '../components/ui/StatusBadge.jsx';
import DateRangeField from '../components/DateRangeField.jsx';
import CrossBatchCandidateComparison from '../components/CrossBatchCandidateComparison.jsx';
import { downloadSelectedScreeningsCsv, getScreenings } from '../services/screeningService.js';

function formatDate(value) { return new Date(value).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }); }
function displayStatus(value) { return String(value || 'pending').replaceAll('_', ' '); }
function compactJobLabel(value, max = 64) {
  const text = String(value || 'Untitled job').replace(/\s+/g, ' ').trim();
  return text.length > max ? `${text.slice(0, max - 1).trimEnd()}…` : text;
}

export default function ScreeningHistoryPage() {
  const [comparisonMode, setComparisonMode] = useState(false); const [items, setItems] = useState([]); const [selectedIds, setSelectedIds] = useState([]); const [loading, setLoading] = useState(true); const [downloading, setDownloading] = useState(false); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState('all'); const [jobFilter, setJobFilter] = useState('all'); const [scoreFilter, setScoreFilter] = useState('all'); const [dateFrom, setDateFrom] = useState(''); const [dateTo, setDateTo] = useState('');
  useEffect(() => { let active = true; getScreenings().then((data) => active && setItems(data)).catch((e) => active && setError(e.response?.data?.message || 'Unable to load history.')).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  const jobOptions = useMemo(() => { const map = new Map(); items.forEach((item) => { const key = item.jobDescriptionId || item.jobDescriptionTitle || item.jobDescription; if (key && !map.has(key)) map.set(key, compactJobLabel(item.jobDescriptionTitle || item.jobDescription || 'Untitled job')); }); return [...map.entries()].map(([value, label]) => ({ value, label })).sort((a, b) => a.label.localeCompare(b.label)); }, [items]);
  const comparisonJobs = useMemo(() => jobOptions.filter((job) => items.some((item) => item.jobDescriptionId === job.value)).map((job) => ({ id: job.value, label: job.label })), [items, jobOptions]);
  const filteredItems = useMemo(() => { const query = search.trim().toLowerCase(); const from = dateFrom ? new Date(`${dateFrom}T00:00:00`) : null; const to = dateTo ? new Date(`${dateTo}T23:59:59.999`) : null; return items.filter((item) => { const matchesStatus = statusFilter === 'all' || item.analysisStatus === statusFilter; const jobKey = item.jobDescriptionId || item.jobDescriptionTitle || item.jobDescription; const matchesJob = jobFilter === 'all' || jobKey === jobFilter; const score = Number(item.averageMatchScore); const matchesScore = scoreFilter === 'all' || (Number.isFinite(score) && (scoreFilter === '80-100' ? score >= 80 : scoreFilter === '60-79' ? score >= 60 && score < 80 : scoreFilter === '40-59' ? score >= 40 && score < 60 : score < 40)); const created = new Date(item.createdAt); const matchesDate = (!from || created >= from) && (!to || created <= to); const searchable = [item.jobDescriptionTitle,item.jobDescription,item.primaryFileName,...(item.resumeFileNames || []),item.topCandidateName].filter(Boolean).join(' ').toLowerCase(); return matchesStatus && matchesJob && matchesScore && matchesDate && (!query || searchable.includes(query)); }); }, [items, search, statusFilter, jobFilter, scoreFilter, dateFrom, dateTo]);
  const visibleIds = filteredItems.map((item) => item.id); const allVisibleSelected = visibleIds.length > 0 && visibleIds.every((id) => selectedIds.includes(id));
  function toggleRow(id) { setSelectedIds((current) => current.includes(id) ? current.filter((selectedId) => selectedId !== id) : [...current, id]); }
  function toggleAllVisible() { setSelectedIds((current) => allVisibleSelected ? current.filter((id) => !visibleIds.includes(id)) : [...new Set([...current, ...visibleIds])]); }
  async function handleDownloadSelected() { if (!selectedIds.length) return; try { setDownloading(true); setError(''); await downloadSelectedScreeningsCsv(selectedIds); } catch (e) { setError(e.response?.data?.message || 'Unable to download selected screenings.'); } finally { setDownloading(false); } }
  const inputClass = 'h-11 w-full rounded-xl border border-slate-700 bg-slate-950/60 px-3 text-sm text-white placeholder:text-slate-600 focus:border-brand-400 focus:ring-4 focus:ring-brand-500/10';
  return <div className="space-y-6">
    <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><span className="text-xs font-black uppercase tracking-[.2em] text-brand-400">Candidate operations</span><h1 className="mt-2 text-3xl font-black">Screening history</h1><p className="mt-2 text-sm text-slate-500">Review resume batches, monitor AI analysis, and export selected records.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setComparisonMode((value) => !value)} className="rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-black text-white hover:bg-brand-600">{comparisonMode ? 'Close comparison' : 'Compare candidates'}</button><button disabled={!selectedIds.length || downloading} onClick={handleDownloadSelected} className="rounded-xl border border-slate-700 px-4 py-2.5 text-sm font-bold text-slate-200 hover:bg-slate-800 disabled:opacity-50">{downloading ? 'Preparing CSV…' : `Download CSV${selectedIds.length ? ` (${selectedIds.length})` : ''}`}</button></div></header>
    <section className="space-y-4 rounded-2xl border border-slate-800 bg-[#0b1220] p-4"><div className="grid gap-4 xl:grid-cols-[minmax(260px,1.5fr)_minmax(200px,1fr)_190px_180px_minmax(260px,1fr)]"><label><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">Search history</span><input className={inputClass} type="search" value={search} placeholder="Candidate, resume, or job" onChange={(e) => setSearch(e.target.value)} /></label><label><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">Job description</span><select className={inputClass} value={jobFilter} onChange={(e) => setJobFilter(e.target.value)}><option value="all">All jobs</option>{jobOptions.map((job) => <option key={job.value} value={job.value}>{job.label}</option>)}</select></label><label><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">AI status</span><select className={inputClass} value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="all">All statuses</option><option value="completed">Completed</option><option value="partially_completed">Partially completed</option><option value="processing">Processing</option><option value="failed">Failed</option><option value="pending">Pending</option></select></label><label><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">AI score</span><select className={inputClass} value={scoreFilter} onChange={(e) => setScoreFilter(e.target.value)}><option value="all">All scores</option><option value="80-100">80–100%</option><option value="60-79">60–79%</option><option value="40-59">40–59%</option><option value="0-39">Below 40%</option></select></label><label><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">Date range</span><DateRangeField fromDate={dateFrom} toDate={dateTo} onChange={({ fromDate, toDate }) => { setDateFrom(fromDate); setDateTo(toDate); }} /></label></div><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex h-9 items-center gap-2 text-sm text-slate-500"><strong className="text-lg text-white">{selectedIds.length}</strong> selected {selectedIds.length > 0 && <button className="font-bold text-brand-400" onClick={() => setSelectedIds([])}>Clear</button>}</div><button type="button" className="rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold text-slate-300 hover:bg-slate-800" onClick={() => { setSearch(''); setJobFilter('all'); setStatusFilter('all'); setScoreFilter('all'); setDateFrom(''); setDateTo(''); }}>Reset filters</button></div></section>
    {comparisonMode && <CrossBatchCandidateComparison jobs={comparisonJobs} onClose={() => setComparisonMode(false)} />}
    {error && <div className="rounded-xl border border-rose-500/25 bg-rose-500/10 p-4 text-sm text-rose-300">{error}</div>}
    <div className="overflow-hidden rounded-2xl border border-slate-800 bg-[#0b1220]">
      {loading && <div className="p-12 text-center text-sm text-slate-500">Loading screenings…</div>}
      {!loading && !items.length && <div className="p-12 text-center"><h2 className="text-xl font-black">No screenings yet</h2><p className="mt-2 text-sm text-slate-500">Create your first screening to see it here.</p></div>}
      {!loading && items.length > 0 && !filteredItems.length && <div className="p-12 text-center text-sm text-slate-500">No screenings match your search or filter.</div>}
      {!loading && filteredItems.length > 0 && <div className="overflow-x-auto"><table className="min-w-[1120px] w-full text-left"><thead className="border-b border-slate-800 bg-slate-950/30 text-[10px] uppercase tracking-wider text-slate-500"><tr><th className="w-12 p-4 text-center"><input type="checkbox" checked={allVisibleSelected} onChange={toggleAllVisible} className="h-4 w-4 accent-indigo-500" /></th><th className="p-4">Uploaded resume</th><th className="p-4">Date</th><th className="p-4">Candidates</th><th className="p-4">Avg. score</th><th className="p-4">AI status</th><th className="p-4">Job description</th><th className="p-4" /></tr></thead><tbody className="divide-y divide-slate-800">{filteredItems.map((item) => { const filenames = item.resumeFileNames || []; const extraFileCount = Math.max(0, filenames.length - 1); const isSelected = selectedIds.includes(item.id); return <tr key={item.id} className={isSelected ? 'bg-brand-500/[.07]' : 'hover:bg-white/[.02]'}><td className="p-4 text-center"><input type="checkbox" checked={isSelected} onChange={() => toggleRow(item.id)} className="h-4 w-4 accent-indigo-500" /></td><td className="p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-800 text-[10px] font-black text-brand-400">CV</span><div className="min-w-0"><strong className="block max-w-60 truncate text-sm" title={item.primaryFileName || ''}>{item.primaryFileName || 'Resume filename unavailable'}</strong><span className="text-xs text-slate-500">{extraFileCount > 0 ? `+${extraFileCount} more resume${extraFileCount === 1 ? '' : 's'}` : `${item.totalCandidates} uploaded`}</span></div></div></td><td className="p-4 text-xs text-slate-400">{formatDate(item.createdAt)}</td><td className="p-4"><strong className="block">{item.totalCandidates}</strong><span className="text-xs text-slate-500">{item.analyzedCandidates || 0} analyzed</span></td><td className="p-4"><span className="rounded-full border border-slate-700 bg-slate-900 px-3 py-1.5 text-xs font-black">{item.averageMatchScore === null ? '—' : `${item.averageMatchScore}%`}</span></td><td className="p-4"><StatusBadge status={item.analysisStatus}>{displayStatus(item.analysisStatus)}</StatusBadge></td><td className="max-w-md p-4"><p className="line-clamp-2 text-xs leading-5 text-slate-500" title={item.jobDescription}>{item.jobDescription}</p></td><td className="p-4"><Link className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-bold hover:bg-slate-800" to={`/screenings/${item.id}`}>View</Link></td></tr>; })}</tbody></table></div>}
    </div>
  </div>;
}
