import React, { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../context/AuthContext.jsx';
import { ROLE_LABELS, ROLES } from '../constants/roles.js';
import {
  createOrganizationUser,
  deleteOrganizationUser,
  getOrganizationUsers,
  resendOrganizationInvitation,
  updateOrganizationUser,
} from '../services/userService.js';

const roles = Object.values(ROLES);
const fieldClass = 'w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5 text-sm text-white outline-none focus:border-brand-400 focus:ring-4 focus:ring-brand-500/10';

function RoleBadge({ role }) {
  const styles = { admin: 'border-violet-500/30 bg-violet-500/10 text-violet-300', recruiter: 'border-blue-500/30 bg-blue-500/10 text-blue-300', hiring_manager: 'border-amber-500/30 bg-amber-500/10 text-amber-300', interviewer: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' };
  return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-black ${styles[role] || styles.recruiter}`}>{ROLE_LABELS[role] || role}</span>;
}

export default function UserManagementPage() {
  const { user: currentUser } = useAuth();
  const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [savingId, setSavingId] = useState(''); const [creating, setCreating] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const [query, setQuery] = useState(''); const [roleFilter, setRoleFilter] = useState('all'); const [statusFilter, setStatusFilter] = useState('all');
  const [temporaryCredentials, setTemporaryCredentials] = useState(null);
  const [form, setForm] = useState({ name: '', email: '', password: '', role: ROLES.RECRUITER });

  async function loadUsers() { setLoading(true); setError(''); try { setUsers(await getOrganizationUsers()); } catch (err) { setError(err.response?.data?.message || 'Unable to load team members.'); } finally { setLoading(false); } }
  useEffect(() => { loadUsers(); }, []);
  const activeCount = useMemo(() => users.filter((item) => item.isActive).length, [users]);
  const filteredUsers = useMemo(() => users.filter((member) => {
    const matchQuery = `${member.name} ${member.email}`.toLowerCase().includes(query.toLowerCase());
    const matchRole = roleFilter === 'all' || member.role === roleFilter;
    const matchStatus = statusFilter === 'all' || (statusFilter === 'active' ? member.isActive : !member.isActive);
    return matchQuery && matchRole && matchStatus;
  }), [users, query, roleFilter, statusFilter]);

  async function submit(event) { event.preventDefault(); setCreating(true); setError(''); setSuccess(''); setTemporaryCredentials(null); try { const created = await createOrganizationUser({ ...form, name: form.name.trim(), email: form.email.trim() }); setUsers((current) => [...current, created]); setTemporaryCredentials({ email: created.email, password: form.password }); setForm({ name: '', email: '', password: '', role: ROLES.RECRUITER }); setSuccess('Team member created. Share the temporary credentials securely.'); } catch (err) { setError(err.response?.data?.message || 'Unable to create team member.'); } finally { setCreating(false); } }
  async function updateMember(member, payload) { setSavingId(member.id); setError(''); setSuccess(''); try { const updated = await updateOrganizationUser(member.id, payload); setUsers((current) => current.map((item) => item.id === updated.id ? updated : item)); setSuccess('Team member updated.'); } catch (err) { setError(err.response?.data?.message || 'Unable to update team member.'); } finally { setSavingId(''); } }
  async function resend(member) { if (!window.confirm(`Generate new temporary credentials for ${member.name}?`)) return; setSavingId(member.id); setError(''); setSuccess(''); try { const data = await resendOrganizationInvitation(member.id); setUsers((current) => current.map((item) => item.id === data.user.id ? data.user : item)); setTemporaryCredentials({ email: data.user.email, password: data.temporaryPassword }); setSuccess(data.message); } catch (err) { setError(err.response?.data?.message || 'Unable to regenerate invitation.'); } finally { setSavingId(''); } }
  async function remove(member) { if (!window.confirm(`Remove ${member.name} from this organization?`)) return; setSavingId(member.id); setError(''); setSuccess(''); try { await deleteOrganizationUser(member.id); setUsers((current) => current.filter((item) => item.id !== member.id)); setSuccess('Team member removed.'); } catch (err) { setError(err.response?.data?.message || 'Unable to remove team member.'); } finally { setSavingId(''); } }

  return <div className="space-y-6">
    <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><span className="text-xs font-black uppercase tracking-[.2em] text-brand-400">Administration</span><h1 className="mt-2 text-3xl font-black">Team & roles</h1><p className="mt-2 text-sm text-slate-400">Manage access for {currentUser?.organization?.name || 'your organization'}.</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 px-4 py-3 text-sm"><strong className="text-white">{activeCount}</strong><span className="ml-2 text-slate-500">active users</span></div></header>
    {(error || success) && <div className={`rounded-xl border p-3 text-sm ${error ? 'border-rose-500/30 bg-rose-500/10 text-rose-300' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'}`}>{error || success}</div>}
    {temporaryCredentials && <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-100"><strong className="block">Temporary credentials</strong><div className="mt-2 grid gap-2 md:grid-cols-2"><code className="rounded-lg bg-black/20 px-3 py-2">{temporaryCredentials.email}</code><code className="rounded-lg bg-black/20 px-3 py-2">{temporaryCredentials.password}</code></div><p className="mt-2 text-xs text-amber-200/70">Copy these now. The password is shown only in this session.</p></div>}
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
      <div className="overflow-hidden rounded-2xl border border-slate-800 bg-[#0b1220]"><div className="border-b border-slate-800 p-5"><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_190px_160px]"><input className={fieldClass} placeholder="Search name or email" value={query} onChange={(e) => setQuery(e.target.value)} /><select className={fieldClass} value={roleFilter} onChange={(e) => setRoleFilter(e.target.value)}><option value="all">All roles</option>{roles.map((role) => <option key={role} value={role}>{ROLE_LABELS[role]}</option>)}</select><select className={fieldClass} value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div>
        {loading ? <div className="p-8 text-sm text-slate-400">Loading team members…</div> : filteredUsers.length === 0 ? <div className="p-8 text-sm text-slate-400">No team members match the filters.</div> : <div className="divide-y divide-slate-800">{filteredUsers.map((member) => { const isSelf = member.id === currentUser?.id; return <div key={member.id} className="grid gap-4 p-5 lg:grid-cols-[minmax(0,1fr)_210px_260px] lg:items-center"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-slate-800 font-black">{member.name?.slice(0,1).toUpperCase()}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="truncate">{member.name}</strong>{isSelf && <span className="text-xs text-slate-500">You</span>}{member.mustChangePassword && <span className="rounded-full bg-amber-500/10 px-2 py-1 text-[10px] font-black text-amber-300">Password pending</span>}</div><p className="truncate text-sm text-slate-500">{member.email}</p></div></div><div><select className={fieldClass} value={member.role} disabled={savingId === member.id || isSelf} onChange={(e) => updateMember(member, { role: e.target.value })}>{roles.map((role) => <option key={role} value={role}>{ROLE_LABELS[role]}</option>)}</select><div className="mt-2"><RoleBadge role={member.role} /></div></div><div className="grid grid-cols-3 gap-2"><button disabled={savingId === member.id || isSelf} onClick={() => updateMember(member,{ isActive: !member.isActive })} className={`rounded-xl border px-2 py-2 text-xs font-black disabled:opacity-40 ${member.isActive ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : 'border-slate-700 text-slate-400'}`}>{member.isActive ? 'Active' : 'Inactive'}</button><button disabled={savingId === member.id || isSelf} onClick={() => resend(member)} className="rounded-xl border border-slate-700 px-2 py-2 text-xs font-black text-slate-300 hover:bg-slate-800 disabled:opacity-40">Reset invite</button><button disabled={savingId === member.id || isSelf} onClick={() => remove(member)} className="rounded-xl border border-rose-500/30 px-2 py-2 text-xs font-black text-rose-300 hover:bg-rose-500/10 disabled:opacity-40">Remove</button></div></div>; })}</div>}
      </div>
      <form onSubmit={submit} className="h-fit rounded-2xl border border-slate-800 bg-[#0b1220] p-5 xl:sticky xl:top-24"><h2 className="font-black">Invite team member</h2><p className="mt-1 text-xs leading-5 text-slate-500">Create temporary credentials. The user must change the password on first login.</p><div className="mt-5 space-y-4"><label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">Full name</span><input className={fieldClass} required minLength="2" value={form.name} onChange={(e) => setForm((v) => ({...v,name:e.target.value}))} /></label><label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">Work email</span><input className={fieldClass} type="email" required value={form.email} onChange={(e) => setForm((v) => ({...v,email:e.target.value}))} /></label><label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">Temporary password</span><input className={fieldClass} type="password" required minLength="8" value={form.password} onChange={(e) => setForm((v) => ({...v,password:e.target.value}))} /></label><label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">Role</span><select className={fieldClass} value={form.role} onChange={(e) => setForm((v) => ({...v,role:e.target.value}))}>{roles.map((role) => <option key={role} value={role}>{ROLE_LABELS[role]}</option>)}</select></label><button disabled={creating} className="w-full rounded-xl bg-brand-500 px-4 py-3 text-sm font-black text-white hover:bg-brand-600 disabled:opacity-60">{creating ? 'Creating…' : 'Create invitation'}</button></div></form>
    </section>
  </div>;
}
