import React, { useState } from 'react';
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useCandidateAuth } from '../../context/CandidateAuthContext.jsx';

function EyeIcon({ visible }) { return visible ? <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 3l18 18M10.6 10.7a2 2 0 0 0 2.7 2.7M9.9 4.2A10.8 10.8 0 0 1 12 4c5.5 0 9 5.1 9 8a8.3 8.3 0 0 1-2 3.7M6.6 6.6C4.2 8.2 3 10.5 3 12c0 2.9 3.5 8 9 8a9.7 9.7 0 0 0 3.3-.6" strokeLinecap="round" strokeLinejoin="round" /></svg> : <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 12c0-2.9 3.5-8 9-8s9 5.1 9 8-3.5 8-9 8-9-5.1-9-8Z" /><circle cx="12" cy="12" r="3" /></svg>; }

export default function CandidateLoginPage() {
  const { account, login } = useCandidateAuth(); const navigate = useNavigate(); const location = useLocation();
  const [form, setForm] = useState({ email: '', password: '' }); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  if (account) return <Navigate to={account.mustChangePassword ? '/candidate/change-password' : '/candidate/dashboard'} replace />;
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { const data = await login({ email: form.email.trim().toLowerCase(), password: form.password }); const fallback = data.account.mustChangePassword ? '/candidate/change-password' : '/candidate/dashboard'; const requested = location.state?.from?.startsWith('/candidate/') ? location.state.from : fallback; navigate(data.account.mustChangePassword ? '/candidate/change-password' : requested, { replace: true }); } catch (e) { setError(e.response?.data?.message || 'Unable to sign in to the candidate portal.'); } finally { setLoading(false); } }
  const field = 'w-full rounded-xl border border-slate-700 bg-slate-950/70 px-4 py-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-brand-400 focus:ring-4 focus:ring-brand-500/10';
  return <main className="min-h-screen bg-[#070b14] text-white lg:grid lg:grid-cols-[minmax(0,1.05fr)_minmax(430px,.95fr)]">
    <aside className="relative hidden overflow-hidden border-r border-slate-800 bg-[#09111f] p-12 lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-20 top-14 h-80 w-80 rounded-full bg-brand-500/20 blur-3xl" /><div className="relative flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-brand-500 text-xl font-black">T</span><div><strong className="block text-xl">TalentLens AI</strong><span className="text-sm text-slate-500">Candidate experience portal</span></div></div><div className="relative max-w-xl"><span className="text-xs font-black uppercase tracking-[.2em] text-brand-400">Your next opportunity</span><h1 className="mt-4 text-5xl font-black leading-tight">Complete your AI interview with confidence.</h1><p className="mt-6 text-lg leading-8 text-slate-400">Review your invitation, prepare your camera and microphone, and complete a secure one-question-at-a-time interview.</p><div className="mt-10 grid gap-4">{['Private candidate-only workspace','Audio and video interview experience','Progress saved securely'].map((item, i)=><div key={item} className="flex items-center gap-4 rounded-2xl border border-slate-800 bg-white/[.03] p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-500/15 text-sm font-black text-brand-300">0{i+1}</span><strong>{item}</strong></div>)}</div></div><p className="relative text-sm text-slate-500">Need help? Contact the recruiter who sent your invitation.</p></aside>
    <section className="flex min-h-screen items-center justify-center px-5 py-10 md:px-10"><div className="w-full max-w-[460px] rounded-3xl border border-slate-800 bg-[#0b1220] p-7 shadow-2xl shadow-black/30 sm:p-10"><div className="mb-8 flex items-center gap-3 lg:hidden"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-500 text-lg font-black">T</span><div><strong className="block text-xl">TalentLens Candidate</strong><span className="text-sm text-slate-500">Secure interview access</span></div></div><span className="text-xs font-black uppercase tracking-[.18em] text-brand-400">Candidate portal</span><h1 className="mt-3 text-3xl font-black">Welcome back</h1><p className="mt-2 text-sm leading-6 text-slate-400">Use the email address and password from your interview invitation.</p><form onSubmit={submit} className="mt-7 space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold text-slate-300">Email address</span><input className={field} type="email" required autoComplete="email" value={form.email} onChange={(e)=>setForm((c)=>({...c,email:e.target.value}))} placeholder="candidate@example.com" /></label><label className="block"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-bold text-slate-300">Password</span><Link to="/candidate/forgot-password" className="text-xs font-bold text-brand-400 hover:text-brand-300">Forgot password?</Link></div><div className="relative"><input className={`${field} pr-12`} type={showPassword?'text':'password'} required autoComplete="current-password" value={form.password} onChange={(e)=>setForm((c)=>({...c,password:e.target.value}))} placeholder="Enter your password" /><button type="button" onClick={()=>setShowPassword((v)=>!v)} className="absolute inset-y-0 right-1 grid w-11 place-items-center rounded-lg text-slate-400 hover:bg-white/5 hover:text-white" aria-label={showPassword?'Hide password':'Show password'}><EyeIcon visible={showPassword}/></button></div></label>{error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-300">{error}</div>}<button disabled={loading} className="w-full rounded-xl bg-brand-500 px-4 py-3.5 text-sm font-black text-white transition hover:bg-brand-600 disabled:opacity-60">{loading?'Signing in…':'Sign in securely'}</button></form><p className="mt-6 text-center text-xs leading-5 text-slate-600">This portal is available only to candidates invited by an organization.</p></div></section>
  </main>;
}
